name = "celo-health-check"
main = "health-check-worker.js"
compatibility_date = "2023-01-01"

# KV namespace for tracking backend health status
# This should be the same KV namespace used by the RPC workers
kv_namespaces = [
  { binding = "HEALTH_KV", id = "$HEALTH_KV_ID", preview_id = "$HEALTH_KV_PREVIEW_ID" }
]

# Run the health check every 5 minutes
[triggers]
crons = ["*/5 * * * *"]