name = "celo-health-check"
main = "health-check-worker.js"
compatibility_date = "2023-01-01"
account_id = "$CLOUDFLARE_ACCOUNT_ID"
workers_dev = false
route = "health.celo-community.org/*"

# Environment variables
[vars]
# These variables are used for Cloudflare API access to purge cache
CF_ACCOUNT_ID = "$CLOUDFLARE_ACCOUNT_ID"
CF_ZONE_ID = "$CLOUDFLARE_ZONE_ID"
CF_API_TOKEN = "$CLOUDFLARE_API_TOKEN"

# KV namespace for tracking backend health status
# This should be the same KV namespace used by the RPC workers
kv_namespaces = [
  { binding = "HEALTH_KV", id = "$HEALTH_KV_ID", preview_id = "$HEALTH_KV_PREVIEW_ID" },
  { binding = "STATIC_CONTENT_KV", id = "$STATIC_CONTENT_KV_ID", preview_id = "$STATIC_CONTENT_KV_PREVIEW_ID" }
]

# Include validator-addresses.json files as assets
[site]
bucket = "./site"

# Run the health check every 15 minutes
[triggers]
crons = ["*/15 * * * *"]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.