name = "celo-mainnet-rpc"
account_id = "$CLOUDFLARE_ACCOUNT_ID"
workers_dev = false
route = "rpc.celo-community.org/*"
compatibility_date = "2023-01-01"
main = "index.js"

[vars]
ENVIRONMENT = "mainnet"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[[unsafe.bindings]]
name = "MY_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"  # Ensure this number is unique within your account
simple = { limit = 1000, period = 60 }

# KV namespace for tracking backend health status
[[kv_namespaces]]
binding = "HEALTH_KV"
id = "$HEALTH_KV_ID"
preview_id = "$HEALTH_KV_PREVIEW_ID"

# Service binding for direct communication with the health check worker
[[services]]
binding = "HEALTH_CHECK_WORKER"
service = "celo-health-check"
environment = "production"
