name = "celo-mainnet-rpc"
type = "javascript"
account_id = "$CLOUDFLARE_ACCOUNT_ID"
workers_dev = false
route = "rpc.mainnet.celo.org/*"
zone_id = "$CLOUDFLARE_ZONE_ID"
compatibility_date = "2023-01-01"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[vars]
ENVIRONMENT = "mainnet"