name = "celo-alfajores-rpc"
type = "javascript"
account_id = "your-account-id"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-01-01"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"