name = "celo-alfajores-rpc"
account_id = "$CLOUDFLARE_ACCOUNT_ID"
workers_dev = false
route = "alfajores-rpc.celo-community.org/*"
compatibility_date = "2023-01-01"
main = "index.js"

[vars]
ENVIRONMENT = "alfajores"