name = "celo-baklava-rpc"
account_id = "$CLOUDFLARE_ACCOUNT_ID"
workers_dev = false
route = "baklava-rpc.celo-community.org/*"
compatibility_date = "2023-01-01"
main = "index.js"

[vars]
ENVIRONMENT = "baklava"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[[unsafe.bindings]]
name = "MY_RATE_LIMITER"
type = "ratelimit"
namespace_id = "3001"  # Ensure this number is unique within your account
simple = { limit = 1000, period = 60 }