name: Update RPC Servers

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write
  pull-requests: write

jobs:
  update-rpc-servers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install axios
      
      - name: Install celocli
        run: npm install -g @celo/celocli
      
      - name: Update RPC servers
        run: node update-rpc-servers.js
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: 'Update RPC servers'
          title: 'Update RPC servers'
          body: |
            This PR updates the RPC server lists based on:
            - Blockchain query using celocli
            - Health checks of all RPC servers
            
            Updated on: ${{ github.event.repository.updated_at }}
          branch: update-rpc-servers
          delete-branch: true